app/__init__.py
from flask import Flask, current_app
# logging
import logging
from logging.handlers import RotatingFileHandler
# configuration
from config import Config

# international
from flask_babel import Babel, lazy_gettext as _l
from babel import negotiate_locale
from flask import request
babel = Babel()
from flask_babel_js import BabelJS
babel_js = BabelJS()
# DB
from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()
# DB migration
from flask_migrate import Migrate
migrate = Migrate()
# login Manager
from flask_login import LoginManager
login = LoginManager()
login.login_message = _l('Please login to access this page.')

import os

def create_app(config_class=Config):
    # ini app
    app = Flask(__name__)
    # db
    db.init_app(app)
    app.app_context().push()
    db.create_all()
    migrate.init_app(app, db)
    # login
    login.init_app(app)
    # babel
    babel.init_app(app)
    babel_js.init_app(app)
    # add config
    app.config.from_object(config_class)
    app.app_context().push()

    # the main of the app
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)
    # editor
    from app.editor import bp as editor_bp
    app.register_blueprint(editor_bp)

    # logs
    if not os.path.exists('logs'):
        os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/oauth.log',
                                           maxBytes=10240, backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s '
            '[in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)
    app.logger.setLevel(logging.INFO)
    app.logger.info('Flask example startup')

    return app

# international
@babel.localeselector
def get_locale():
    preferred = [x.replace('-', '_') for x in request.accept_languages.values()]
    return negotiate_locale(preferred, current_app.config['LANGUAGES'])

from app import models_editor

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import jsonify, current_app, send_from_directory
# blueprint
from app.main import bp

# global values
from flask import g

# check before every request
@bp.before_request
def before_request():
    pass

# after every request
@bp.after_request
def set_response_headers(response):
    return response

@bp.route('/')
def root():
    return jsonify({"name": current_app.config['NAME'], 'version': current_app.config['VERSION']})

app/templates/base_menu.html
            <!-- right side of the mur2 menu -->
            <div id="mur2menu" class="toolbar-button">

                <div id="mur2menutop">
                    <label class="toolbar fas fa-bars" for="id_side_menu" title="{{ _('Close Side Menu') }}" ></label>
                </div>

                <!-- <input class="control-input" id="id_search" type="checkbox" name="source_type" > -->
                <div id="mur2menu_link" class="sidebarLinks">
                    <a class="toolbar-button control-item  " title="{{ _('Home') }}" href="{{ url_for('main.root') }}">{{ _("Home") }}</a>
                    {% if not current_user.is_anonymous %}
                    <a class="toolbar-button control-item" title="{{ _('Editor') }}" href="{{ url_for('editor.editor', articleid='-1') }}">{{ _("Editor") }}</a>
                    <a class="toolbar-button control-item " title="{{ _('Media') }}" href="{{ url_for('editor.media') }}">{{ _("Media") }}</a>
                    {% else %}
                    <a class="toolbar-button control-item" title="{{ _('Editor') }}" href="{{ url_for('editor.free_editor') }}">{{ _("Editor") }}</a>
                    {% endif %}
                    <input class="choice_toolbar control-input" id="id_dark_menu" type="checkbox" onclick="switchtheme();" name="source_type" >
                    <label class="toolbar-button control-item" for="id_dark_menu" title="{{ _('Switch theme') }}" >{{ _('Switch theme') }}</label>
                </div>
            </div>